###################################################################

# Created by write_sdc on Sat Sep 26 19:52:30 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_uncertainty 1.5  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  0  [get_ports mmio_we]
set_input_delay -clock clk  0  [get_ports mmio_re]
set_input_delay -clock clk  0  [get_ports {mmio_addr[7]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[6]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[5]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[4]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[3]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[2]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[1]}]
set_input_delay -clock clk  0  [get_ports {mmio_addr[0]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[31]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[30]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[29]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[28]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[27]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[26]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[25]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[24]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[23]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[22]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[21]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[20]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[19]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[18]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[17]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[16]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[15]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[14]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[13]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[12]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[11]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[10]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[9]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[8]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[7]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[6]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[5]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[4]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[3]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[2]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[1]}]
set_input_delay -clock clk  0  [get_ports {mmio_wdata[0]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[31]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[30]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[29]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[28]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[27]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[26]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[25]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[24]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[23]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[22]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[21]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[20]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[19]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[18]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[17]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[16]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[15]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[14]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[13]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[12]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[11]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[10]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[9]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[8]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[7]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[6]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[5]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[4]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[3]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[2]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[1]}]
set_output_delay -clock clk  0  [get_ports {mmio_rdata[0]}]
set_output_delay -clock clk  0  [get_ports irq]
